<project xmlns="http://maven.apache.org/POM/4.0.0">
 <modelVersion>4.0.0</modelVersion>
 <groupId>kz.lab</groupId>
 <artifactId>servlet-lab</artifactId>
 <version>1.0</version>
 <packaging>war</packaging>
 <properties>
   <maven.compiler.source>17</maven.compiler.source>
   <maven.compiler.target>17</maven.compiler.target>
   <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
   <failOnMissingWebXml>false</failOnMissingWebXml>
 </properties>
 <dependencies>
   <dependency>
     <groupId>javax.servlet</groupId>
     <artifactId>javax.servlet-api</artifactId>
     <version>4.0.1</version>
     <scope>provided</scope>
   </dependency>
 </dependencies>
 <build>
   <finalName>lab</finalName>
   <plugins>
     <plugin>
       <groupId>org.eclipse.jetty</groupId>
       <artifactId>jetty-maven-plugin</artifactId>
       <version>9.4.54.v20240208</version>
       <configuration>
         <httpConnector><port>8080</port></httpConnector>
         <webApp><contextPath>/lab</contextPath></webApp>
       </configuration>
     </plugin>
   </plugins>
 </build>
</project>
